apiVersion: v1
kind: Secret
metadata:
  name: fabric-ca-secrets
type: Opaque
data:
  tls-ca-adminpw:  {{ .Values.orgs.tls.ca.adminpw | b64enc | quote }}
  orderer-ca-adminpw: {{.Values.orgs.orderer.ca.adminpw | b64enc | quote }}
  {{- range $idx, $peer := .Values.orgs.peer }}
  org{{$idx}}-ca-adminpw: {{ .ca.adminpw | b64enc | quote }}
  {{- end }}