apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-configmap-scripts
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-configmap-config
data:
{{ (.Files.Glob "config/*.yaml").AsConfig | indent 2 }}
